# ======================================================================
# GENERATED BY DOCDRIVEN - DO NOT EDIT MANUALLY
# Owner: docdriven
# ======================================================================
# 
# This file was automatically generated from documented codeblocks.
# To modify this file, update the source documentation and regenerate.
# 
# Source: docs/tutorial.md[python][0]
# ======================================================================

def main():
    print("Hello from docdriven!")
    print("Running in the same repository as the docs!")
    return 0

if __name__ == "__main__":
    exit(main())
