# ======================================================================
# GENERATED BY DOCDRIVEN - DO NOT EDIT MANUALLY
# Owner: docdriven
# ======================================================================
# 
# This file was automatically generated from documented codeblocks.
# To modify this file, update the source documentation and regenerate.
# 
# Source: docs/tutorial.md[python][1]
# ======================================================================

def calculate_sum(a, b):
    """Add two numbers together."""
    return a + b

def greet(name):
    """Greet a user by name."""
    return f"Hello, {name}!"
