let extension_of_path path =
  match Filename.extension path with
  | "" -> None
  | ext -> Some (String.lowercase_ascii ext)

let comment_style = function
  | ".py" | ".sh" | ".rb" | ".pl" | ".r" | ".yaml" | ".yml" | ".toml" | ".imba" -> `Hash
  | ".js" | ".ts" | ".jsx" | ".tsx" | ".c" | ".cpp" | ".h" | ".hpp" 
  | ".java" | ".cs" | ".go" | ".rs" | ".swift" | ".kt" | ".scala" 
  | ".php" | ".css" | ".scss" | ".less" -> `Slash
  | ".sql" | ".lua" | ".hs" -> `DoubleDash
  | ".ml" | ".mli" | ".ocaml" -> `Paren
  | ".html" | ".xml" | ".svg" -> `HtmlXml
  | ".vim" -> `Quote
  | ".el" | ".lisp" | ".scm" | ".clj" -> `Semicolon
  | ".tex" -> `Percent
  | ".asm" | ".s" -> `Semicolon
  | _ -> `Hash

let format_comment style text =
  let lines = String.split_on_char '\n' text in
  match style with
  | `Hash -> List.map (fun l -> "# " ^ l) lines
  | `Slash -> ["//"] @ List.map (fun l -> "// " ^ l) lines @ ["//"]
  | `DoubleDash -> List.map (fun l -> "-- " ^ l) lines
  | `Paren -> ["(*"] @ List.map (fun l -> " * " ^ l) lines @ [" *)"]
  | `HtmlXml -> ["<!--"] @ List.map (fun l -> "  " ^ l) lines @ ["-->"]
  | `Quote -> List.map (fun l -> "\" " ^ l) lines
  | `Semicolon -> List.map (fun l -> "; " ^ l) lines
  | `Percent -> List.map (fun l -> "% " ^ l) lines

let generate_header path owner sources =
  let source_list = String.concat ", " sources in
  let border = String.make 70 '=' in
  let warning = [
    border;
    "GENERATED BY DOCDRIVEN - DO NOT EDIT MANUALLY";
    "Owner: " ^ owner;
    border;
    "";
    "This file was automatically generated from documented codeblocks.";
    "To modify this file, update the source documentation and regenerate.";
    "";
    "Source: " ^ source_list;
    border;
  ] in
  match extension_of_path path with
  | Some ext ->
      let style = comment_style ext in
      let lines = format_comment style (String.concat "\n" warning) in
      String.concat "\n" lines ^ "\n\n"
  | None -> ""

let extract_owner_from_file path =
  try
    if not (Sys.file_exists path) then None
    else
      let ic = open_in path in
      let rec read_lines count =
        if count > 10 then None (* Only check first 10 lines *)
        else
          try
            let line = input_line ic in
            (* Match "Owner: <name>" in various comment styles *)
            let owner_pattern = Re.Perl.compile_pat {|Owner:\s*(.+)|} in
            match Re.exec_opt owner_pattern line with
            | Some groups ->
                close_in ic;
                Some (String.trim (Re.Group.get groups 1))
            | None -> read_lines (count + 1)
          with End_of_file ->
            close_in ic;
            None
      in
      read_lines 0
  with _ -> None
