let extension_of_path path =
  match Filename.extension path with
  | "" -> None
  | ext -> Some (String.lowercase_ascii ext)

let comment_style = function
  | ".py" | ".sh" | ".rb" | ".pl" | ".r" | ".yaml" | ".yml" | ".toml" -> `Hash
  | ".js" | ".ts" | ".jsx" | ".tsx" | ".c" | ".cpp" | ".h" | ".hpp" 
  | ".java" | ".cs" | ".go" | ".rs" | ".swift" | ".kt" | ".scala" 
  | ".php" | ".css" | ".scss" | ".less" -> `Slash
  | ".sql" | ".lua" | ".hs" -> `DoubleDash
  | ".ml" | ".mli" | ".ocaml" -> `Paren
  | ".html" | ".xml" | ".svg" -> `HtmlXml
  | ".vim" -> `Quote
  | ".el" | ".lisp" | ".scm" | ".clj" -> `Semicolon
  | ".tex" -> `Percent
  | ".asm" | ".s" -> `Semicolon
  | _ -> `Hash

let format_comment style text =
  let lines = String.split_on_char '\n' text in
  match style with
  | `Hash -> List.map (fun l -> "# " ^ l) lines
  | `Slash -> ["//"] @ List.map (fun l -> "// " ^ l) lines @ ["//"]
  | `DoubleDash -> List.map (fun l -> "-- " ^ l) lines
  | `Paren -> ["(*"] @ List.map (fun l -> " * " ^ l) lines @ [" *)"]
  | `HtmlXml -> ["<!--"] @ List.map (fun l -> "  " ^ l) lines @ ["-->"]
  | `Quote -> List.map (fun l -> "\" " ^ l) lines
  | `Semicolon -> List.map (fun l -> "; " ^ l) lines
  | `Percent -> List.map (fun l -> "% " ^ l) lines

let generate_header path sources =
  let source_list = String.concat ", " sources in
  let warning = [
    "GENERATED BY DOCDRIVEN - DO NOT EDIT";
    "";
    "This file was automatically generated from documented codeblocks.";
    "To modify this file, update the source documentation and regenerate.";
    "";
    "Sources: " ^ source_list;
  ] in
  match extension_of_path path with
  | Some ext ->
      let style = comment_style ext in
      let lines = format_comment style (String.concat "\n" warning) in
      String.concat "\n" lines ^ "\n\n"
  | None -> ""
