# ======================================================================
# GENERATED BY DOCDRIVEN - DO NOT EDIT MANUALLY
# Owner: TestUser
# ======================================================================
#
# This file was automatically generated from documented codeblocks.
# To modify this file, update the source documentation and regenerate.
#
# Source: tutorial.md[python][0]
# ======================================================================

def main():
    print("Hello from docdriven!")
    return 0

if __name__ == "__main__":
    exit(main())
