-- ======================================================================
-- GENERATED BY DOCDRIVEN - DO NOT EDIT MANUALLY
-- Owner: docdriven
-- ======================================================================
-- 
-- This file was automatically generated from documented codeblocks.
-- To modify this file, update the source documentation and regenerate.
-- 
-- Source: docs/tutorial.md[sql][0]
-- ======================================================================

CREATE TABLE users (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_users_email ON users(email);
