-- ======================================================================
-- GENERATED BY DOCDRIVEN - DO NOT EDIT MANUALLY
-- Owner: TestUser
-- ======================================================================
--
-- This file was automatically generated from documented codeblocks.
-- To modify this file, update the source documentation and regenerate.
--
-- Source: tutorial.md[sql][0]
-- ======================================================================

CREATE TABLE users (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE
);
